Repository Rust-Python-Packaging/pyver, pull requests merged in 2022-09, with the labels that each got.

#6 [`#4`] Created Github Actions
  .github/workflows/checks.yml
  .github/workflows/md_checks.yml
Labels: enhancement, maintenance

#10 Enhance README documentation and add CI jobs
  .github/workflows/build.yml
  .github/workflows/checks.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/md_checks.yml
  .github/workflows/package.yml
  .github/workflows/tests.yml
  .rustfmt.toml
  CHANGELOG.md
  Cargo.toml
  LICENSE
  README.md
  deny.toml
  src/lib.rs
Labels: documentation, ci/cd

#11 [`#2`] Moved tests to their respective files
  src/ids/dev_id.rs
  src/ids/post_id.rs
  src/ids/pre_id.rs
  src/ids/release_id.rs
  src/lib.rs
Labels: maintenance

#14 [`#12`] Created check.yml
  .github/workflows/check.yml
  .github/workflows/tests.yml
Labels: ci/cd

#15 [`#1`] Improve Rust Docs
  src/ids/dev_id.rs
  src/ids/mod.rs
  src/ids/post_id.rs
  src/ids/pre_id.rs
  src/lib.rs
  src/validator.rs
Labels: documentation

#18 Add more Caching
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/tests.yml
Labels: ci/cd

#19 Updated Licence to match github template
  LICENSE
Labels: documentation

#20 [`#13`] Change Licence Badge
  README.md
Labels: documentation

#21 [`#16`] Moved PackageVersion to version.rs
  src/lib.rs
  src/version.rs
Labels: enhancement

#22 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
